/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function __wbg_publicparams_free(a: number): void;
export function __wbg_txoref_free(a: number): void;
export function __wbg_authenticatedassetrecord_free(a: number): void;
export function __wbg_clientassetrecord_free(a: number): void;
export function __wbg_assettracerkeypair_free(a: number): void;
export function __wbg_ownermemo_free(a: number): void;
export function __wbg_credentialuserkeypair_free(a: number): void;
export function __wbg_credentialissuerkeypair_free(a: number): void;
export function __wbg_credentialrevealsig_free(a: number): void;
export function __wbg_credentialcommitmentdata_free(a: number): void;
export function __wbg_credentialcommitment_free(a: number): void;
export function __wbg_credentialpok_free(a: number): void;
export function __wbg_credentialcommitmentkey_free(a: number): void;
export function __wbg_assettype_free(a: number): void;
export function __wbg_credential_free(a: number): void;
export function __wbg_signaturerules_free(a: number): void;
export function __wbg_tracingpolicies_free(a: number): void;
export function __wbg_tracingpolicy_free(a: number): void;
export function __wbg_assetrules_free(a: number): void;
export function __wbg_credentialsignature_free(a: number): void;
export function __wbg_transactionbuilder_free(a: number): void;
export function __wbg_feeinputs_free(a: number): void;
export function __wbg_transferoperationbuilder_free(a: number): void;
export function __wbg_bippath_free(a: number): void;
export function __wbg_credissuersecretkey_free(a: number): void;
export function __wbg_credissuerpublickey_free(a: number): void;
export function __wbg_creduserpublickey_free(a: number): void;
export function __wbg_credusersecretkey_free(a: number): void;
export function __wbg_xfrpublickey_free(a: number): void;
export function __wbg_xfrkeypair_free(a: number): void;
export function __wbg_get_xfrkeypair_pub_key(a: number): number;
export function __wbg_set_xfrkeypair_pub_key(a: number, b: number): void;
